### ISSUE TITLE
Suggestion: Vue~ish page transition modes

### ISSUE THREAD

**Issue by panayotoff** [swup/swup#106]
I would suggest adding modes ( in-out and out-in ) to handle page transitions, so it's possible to make more interesting effects, ex. one page pushing the other ( both are visible on the page at the same time for a moment ).

**Comment by andrewjireland** [comment]
+1 to this suggestion.

Currently, I'm getting around this limitation by cloning the existing swup container during the 'out', which I manually remove once the 'in' transition is complete to create this style of effect.

This would allow for a lot more creativity in transitions, which would really enhance swupjs' usability!

**Comment by gmrchk** [comment]
Problem with that approach is that you need to have a custom HTML structure like Barba (although quite a simple one) to be able to work with two containers of different pages during the transition. 

Another problem is that swup is really easy to implement for most of the solutions due to the possibility of defining multiple containers (also independently of things animating on a page), which kind of goes against the "two same containers from different pages" approach. 

Next thing to consider is the fact that swup starts the animation regardless of the next page content being available or not. I consider this a big plus, as a user has immediate feedback of something happening the moment of clicking on a link, which wouldn't be always possible in case of two containers being available at the same time during the transition.

I like the idea suggested to me by @cirmaciu, that the default functionality of replacing content and animation would stay the same or similar, but it would be easier to rewrite this default behavior and the whole process of animating/replacing content would be much more separated into rewritable pieces.

"Ready to go" plugins could be also used to modify this default behavior of swup into most common use cases, like the one you are facing.

Any suggestions?

**Comment by panayotov** [comment]
I totally agree that the current setup handles most cases and is very beginner-friendly. I would actually suggest that this functionality can be added to swup**js**,  where advanced users have more control over the precise timing ( ex. not relying on css-transition/animation events ). 

Imagine the following:

```
{
"animations-mode": "in-out",
"animations-mode-delay": 0,
"animations":  {
    "*" : {
       in(next, element){ //animate element },
       out(next, element){ //animate element }
     }
  }
}
```

animations-mode can be:
**out-in** - default mode, as swup works for now
**in-out** - the `in(next, element)` animation first, then `out(next, element)`

If **animatios-mode-delay** is set to 0 , the in() and out() animation are one after another, not waiting for next() callback.

Also, note the second parameter to  in/out( next,  **element** ) - this should be the dom element 

What do you think?

**Comment by andrewjireland** [comment]
Another thought regarding @panayotov's suggestion. In practice, it would be best to be able to set the mode "in-out" vs "out-in" individually for each animation route which has been defined, rather than as a global option.

In order to keep swup's configuration simple to understand for beginners, defining the mode could also be as simple as just basing the selected mode on the order each stage of the animation is defined. Ie.

Default animation mode (out-in):

`"animations":  {
    "*" : {
       out(next, element){ //animate element },
       in(next, element){ //animate element }
     }
  }` 

Reverse animation mode:

`"animations":  {
    "*" : {
       in(next, element){ //animate element },
       out(next, element){ //animate element }
     }
  }`

**Comment by panayotov** [comment]
I think if it's object, not indexed array, better to make the option explicit. Also, agree that the change should not break existing behavior.

**Comment by gmrchk** [comment]
Thanks for suggestion @panayotov @andrewjireland, it seems great!

However, both suggestions seem to heavily rely on making the swup logic even more complicated and harder to change in the future. Swup is utilizing a set of events that happen during the transition, and changing this order would not be very maintenance/future changes friendly to allow both options of transitions to coexist. Anyhow, I understand the need and I definitely want to go the same way and allow such an option.

What I've been playing around with and trying to figure out is rather making the process of the animation easily adjustable. Currently, this is not the case, as everything is handled in two main big methods. What I would like to achieve is something like this:

```javascript
transition({animateOut, animateIn, requestPromise}) {
    const animateOutPromise = animateOut();    // run animation out
    Promise.all([animateOutPromise, requestPromise])   // wait for animation out to finish and request to resolve
        .then(() => {
            animateIn();
        })
}
```

This is just an example, but the main idea should be clear: having several methods that would contain the main logic of the page transition, that could be changed by more advanced users as needed, or even better, by a plugin for more common use cases like yours.

Thoughts?

**Comment by gmrchk** [comment]
As mentioned before, this suggestion would require a lot of changes and bloat of swup core, which I don't really want to do. Since this thread has been dead for a while, I will close this as "won't implement", as there are other priorities.

I would point out that v2 was released with a bunch of improvements since the beginning of this thread and a plugin could overwrite some of the swup methods and thus, modify the behavior to support this feature. [JS-plugin](https://github.com/swup/js-plugin) should serve as a good example for that, in case someone would like to jump into that direction.
