### ISSUE TITLE
handle display none situations

### ISSUE THREAD

**Issue by Nemo64** [swup/swup#140]
I have some svg's that are hidden on mobile using display none. Since Swup is waiting on their transition, the page change never happens.

I have 2 possible solutions:

1. a timeout. accidents happen, rather a slow page change than no page change.
2. a check if the element can execute a transition. Basically doing the same check as query's `:visible` selector and also maybe checking if `transition-property` is set.

**Comment by Nemo64** [comment]
I now implemented a fairly brutal workaround.

```JavaScript
function handleVisible() {
    const $allElements = $(ANIMATION_SELECTOR);
    const $visibleElements = $allElements.filter(':visible, svg:visible *');
    const $invisibleElements = $allElements.not($visibleElements);
    $visibleElements.addClass('.transition-visible');
    $invisibleElements.removeClass('.transition-visible');
}
swup.on('clickLink', handleVisible);
swup.on('contentReplaced', handleVisible);
```

and then set the animationSelector to `'.transition-visible' + ANIMATION_SELECTOR `

**Comment by gmrchk** [comment]
Hi @Nemo64, 

I think your idea with detecting whether the element can be animated sounds good so we can just ignore waiting in case there is nothing to wait for. In reality, it would mean that even some bugs introduced by swup users (like not setting styles for `transition-*` elements) could lead to transition without animation, instead of no navigation at all. 

That means it would be good to check for two things:
* Is the element visible and "animatable" at all
* Does it have some kind of animated property + transition property 
 
I will need to look into it a bit to come up with correct solution. In case you would like to pitch in, [here](https://github.com/swup/swup/blob/master/src/modules/getAnimationPromises.js) is the code that takes care of detecting the end of animation on elements. 

Thank you for reporting!

**Comment by Nemo64** [comment]
A question: Is there a reason you are not listening to the transitionstart event?

This could be refactored to:
- wait one animation frame for the first transitionstart event and add them to a queue
- until all started transitions haven't ended, still listen for the start event (since the transition could be delayed)
- only go to the next page if all started transitions have ended

This could go as far as completely removing the need for the `transition-*` class since all transitioning elements will indicate that they are transitioning though this event.

**Comment by gmrchk** [comment]
Detecting a transition start before a waiting is definitely a way to go here, as it would prevent swup getting stuck when the user of swup (developer) makes a mistake. 👍 

However, the need for `transition-*` still stays, otherwise swup could be waiting for any element that is transitioning at the time, which can include some hovered elements or other very slow transitions.

**Comment by gmrchk** [comment]
While I do see value in this, I clearly won't get to it. It doesn't seem to be a common problem, so the priority is low.

I will close this and let's see if the problem comes up more often in the future. In case anyone wants to take care of this, I'm always open to PR.
