### ISSUE TITLE
SWUP in Divi

### ISSUE THREAD

**Issue by shawnstom** [swup/swup#150]
I assume there proabably known issues with using SWUP in divi but i havent found any good threads. This is the site I am working on. https://tribusdesignstudio.wpserver.cloud/

I add the options for the container to be the div #main-content. I used jquery to add the class .transition-fade

Page is fading out, but not fading in and the next page i go to is all messed up. I presume css is not loading. 

I added the plugin to reload the scripts but dont thing it solved the problem. 

What are your thoughts on this?

**Comment by Grafikart** [comment]
The problem comes from the fact your JavaScript is not ran after the transition. 
https://swup.js.org/getting-started/reloading-javascript

Since you are using an automated tool I'm not sure there is a workaround for this problem since divi (and some plugins) may not support page being reloaded using Ajax.

**Comment by gmrchk** [comment]
When you add a `transition-fade` class with a jQuery on the frontend, it means the class won't be present in the next loaded page, so that's why the page doesn't animate back in. You can change the default [animation selector](https://swup.js.org/options#animation-selector) option to `#main-content`, and define CSS for that selector instead of `transition-fade`.

FYI: You may also want to check out themes like the [Fade theme](https://swup.js.org/themes/fade-theme), which can help with the animation setup.

The fact that the next page is messed up most likely means the CSS for the pages are loaded separately for each. [Head plugin](https://swup.js.org/plugins/head-plugin) could help with that, which will load any CSS necessary for the current page, as it will replace elements of head tag with the elements present in head tag of the current page. Keep in mind that this loading can take some time, so any styles for layout or such should be placed into a global file that is present on all pages. I'm not sure how DIVI does it, so I can't help with that. 

AS @Grafikart mentioned, some scripts may not be running as well and you should restructure your code a bit, but I guess it could be DIVIs code we are referring to, and you may not have access to it. [Scripts plugin](https://swup.js.org/plugins/scripts-plugin) could help in those situations.
