### ISSUE TITLE
Errors during transition as well as in console. 

### ISSUE THREAD

**Issue by fowlercraig** [swup/swup#163]
Sorry I couldn't be more specific in the title -- hopefully the explanation below clarifies. 

Installed Swup for the first time, followed the directions, but am not having any luck getting it to work properly. 

Currently have an error in the console:

`TypeError: null is not an object (evaluating 't.responseURL=(0,y.getCurrentUrl)()')`

And when I try to navigate between pages, everything fades out per usual, but it ends up being directed to this url:

`typeerror:%20null%20is%20not%20an%20object%20(evaluating%20'document.body.querySelector('[data-swup="'%20+%20i%20+%20'"]').outerHTML%20=%20page.blocks[i]')`

app.js file looks like this:

```
// Swup
import Swup from 'swup';
import SwupBodyClassPlugin from '@swup/body-class-plugin';
import SwupPreloadPlugin from '@swup/preload-plugin';

const swup = new Swup({
  plugins: [
    new SwupBodyClassPlugin(),
    new SwupPreloadPlugin()
  ]
});
```
A little weird -- kinda confused what's happening.

**Comment by gmrchk** [comment]
Hi, 

this is most likely because of a wrong HTML structure, so for example `containers` option is set to `#swup`, but there is no element with that id in the page. The missing title of a page could also be a problem. 

Not sure if it would help in this situation, as I'm trying to add checks for different situations, but in general I would recommend using the [debug plugin](https://swup.js.org/plugins/debug-plugin) as well (not in production).

**Comment by mevanloon** [comment]
Don't want to reopen this, but I ran into this as well and had a lot of trouble finding the issue. 
The Debug plugin didn't give me a lot to go on, I'm afraid. Maybe we could add something in the FAQ about this error?

I know I feel stupid after finding out this one page didn't have the #swup id set, but I feel like we could prevent others from running into it by suggesting it in the error, or something.
