### ISSUE TITLE
./page.html not working

### ISSUE THREAD

**Issue by LauraSophieM** [swup/swup#175]
First of all: your library is great!
I followed the example in your docs and everything works fine... until I use ./page.html instead of /page.html.
Do relative paths not work? What's wrong?

**Comment by Nosrevelk** [comment]
Swup is by default set to do the transition for any link with href attribute starting with the current domain, / or #. 
https://swup.js.org/common-issues

Default behavior can be changed with linkSelector option.
https://swup.js.org/options#link-selector

**Comment by samyun76** [comment]
I'm having the same issue. I write a relative link to another page like this:

`<a href="/pricing.html" class="transition-fade"> home</a>`

And, I get the "Cannot Get pricing.html" error. 

I follow the linki wrote in the VS code and it simply skips back a parent directory and tries to find the file (which the browser cannot find, since it is going to the parent directory and not staying in the current directory). Am I missing something here?

**Comment by AugustMiller** [comment]
`/pricing.html` tells the browser to load `pricing.html` from the root web directory.

Could you describe the relationship between the two pages a bit more?
