### ISSUE TITLE
Make swup work with infinitescroll.js

### ISSUE THREAD

**Issue by dnnsjsk** [swup/swup#181]
Hey,

I am loving swup.js! At the moment I am having some troubles implementing it with infinitescroll.js when I enable rewriting of the URL when a new page has been reached by scrolling. Both libraries work together if I disable rewriting of the current URL.

An example of the problem can be seen here: https://btk.space.press/ - scroll to the bottom and wait till the URL changes to the second page, then click on a tile.

I assume the popState history has to be fed with the entry that infinitescroll.js creates, but this sadly surpasses my current JS skills.

Thanks in advance for any pointers into the right direction.

Best,
Dennis

**Comment by gmrchk** [comment]
It looks like you have several problems there. I will assume you are using the infinite scroll by @desandro. 

Infinite scroll is rewriting the history, which is fine, but we're still on the main page while the history tells us something else, so swup will navigate to the homepage on click of the logo. I would make swup ignore the logo link (leading to the homepage) and use your own listener to go to homepage/scroll to top based on what we need.

Swup doesn't do anything on back/forward when the record in history wasn't created by swup. Since the records in browser history are modified by infinite scroll, we need to change the [skip popstate handling option](https://swup.js.org/options#skip-popstate-handling) to a function that just returns `true` so it handles any history records.

Also (and I think this is the main problem) it seems the infinite scroll is running even when switching to another page. It should be disabled before page leaves (`willReplaceContent` event) and re-enabled if needed. [This](https://swup.js.org/getting-started/reloading-javascript) link could help.

**Comment by dnnsjsk** [comment]
Legend, thank you for the quick reply. I am already using the `willReplaceContent` event to great extent, destroying Infinitescroll.js instance wasn’t on my mind yet, I will try that in conjunction with the popState function.

Is there a particular reason swup doesn’t handle all history records as a default?

**Comment by gmrchk** [comment]
Glad I could help 👍 

It doesn't really happen often that another library is changing browser history as well. However, if that happens, it's good to know that swup can ignore such records, but it doesn't have to. That's the main point of the default option, to show how swup can only work with its own history records, as it's always easy to set it to `() => true`.

**Comment by dnnsjsk** [comment]
So I the URLs are changing correctly now, I am using this for my skipPopStateHandling:

`    skipPopStateHandling: function () {
        return true;
    },`

I am also destroying the infinitescroll instance on content replace, however, the page is not updating when I click back in the browser. It stays on the same page.

![giphy (4)](https://user-images.githubusercontent.com/39319746/62007108-e2f5cf80-b149-11e9-8fd5-d98aec8b9a77.gif)

Any clue why that might be?

**Comment by gmrchk** [comment]
Hi @dnnsjsk, sorry for the delay, holidays and stuff...

When infinite scroll updates DOM with the contents of the next page, the contents should be placed into swup cache as well, so it all works smoothly. It would require a bit of manual tweaking, but [this](https://swup.js.org/api/cache) page should help, otherwise, swup only knows that original page loaded at first. 

But to your problem, I think the problem here is that infinite scroll updates the URL, while there is no new page loaded really, or swup doesn't know about it. That means that once we go back, the URL is changed to the one that swup doesn't know about. Theoretically, swup should load the `/page2` if it doesn't find it in the cache, which clearly doesn't happen, but I would need to have a closer look to find why. Could you provide a demo so we can have a closer look?

Preventing the infinite scroll from updating URL + updating swup cache (when infinite updates DOM) should be the easiest way to achieve what you're looking for I guess.
