### ISSUE TITLE
Sending form without reloading the page

### ISSUE THREAD

**Issue by Kacperell** [swup/swup#183]
Hi! I have form on my website. I use preventDefault(), so I don’t overload the page. 
```
  e.preventDefault();
    axios
        .post(this.action)
        .then(res => {  …
```
Without router ajax query returns me data from my node.js server and I can make changes on the website. On the server it looks like this `res.json(data);`
And this date is my response to Axios.
But when I use swup.js it’s different. Res.json() render pure site with json data. I can’t understand why. I check it in firefox  network monitor normally is status 200 POST Cause XHR. But when I use router Cause is : document .

**Comment by gmrchk** [comment]
Hi @Kacperell, sorry for the delay, holidays and stuff...

I'm not sure I understand the problem since it seems like you don't use swup to send the form and so it probably doesn't have anything to do with the data returned from the server. 

However, I have a feeling like `X-Requested-With` could be the cause here, as swup sets it to a value of `swup` instead of `XMLHttpRequest`. This can be changed with options.
