### ISSUE TITLE
Render cached page and check in background if new content is available and (if any) re-render?

### ISSUE THREAD

**Issue by frederikhors** [swup/swup#194]
I'm sorry it's the first time I see swup: **AMAZING**!

Just one question (coming from Turbolinks): is there a way to load the cached page (just like it happens default way) but check in "background" for new content on the same (dynamic, server-rendered, not SPA, traditional) page and replace the content with new one if available?

**Comment by frederikhors** [comment]
From Turbolinks docs (https://github.com/turbolinks/turbolinks/#understanding-caching):

>... during standard navigation (via Application Visits), Turbolinks will immediately restore the page from cache and display it as a preview while simultaneously loading a fresh copy from the network. This gives the illusion of instantaneous page loads for frequently accessed locations.

**Comment by gmrchk** [comment]
Hi @frederikhors! 👋 

I've been thinking about this a while back. However, swup is mainly meant for animated page transition, so this checking for new content and replacing would create unwanted jumps in content for example.

However, since many people use it to just improve page load speed, this could be interesting feature, that could be quite easily [implemented with a plugin](https://swup.js.org/plugins/create-plugin). Would you like to implement this? I can create a repo for you and add you to the org.
