### ISSUE TITLE
Preload plugin create duplicate images

### ISSUE THREAD

**Issue by ethereal94** [swup/swup#226]
Hi! Preload plugin create duplicate images...
[https://i.ibb.co/Ny6bLFs/swup.png](https://i.ibb.co/Ny6bLFs/swup.png)

As I understand it, this plugin should upload images and then when you go to the page, images should appear immediately without loading.

It works for me like this: the pictures are loaded, then when you go to the page, they are loaded again (create duplicate)... And it's not very beautiful.
Did everything according to the instructions: [https://swup.js.org/plugins/preload-plugin](https://swup.js.org/plugins/preload-plugin)

What could be the problem? Thank!

**Comment by gmrchk** [comment]
Hi, the plugin actually doesn't do anything about images. All it does is preload the html of next page. In case you are seeing the images being downloaded on hover of a link, it's the browser doing it, not swup. 

In case your images are loading again afterwards, it's probably due to one of the following:
- you're running development version on your computer which is often slow even tho it's right there on your computer
- you have a cache disabled in your browser (because of dev tools being open?) which mean nothing is being cached, even images downloaded a second before
- your images are too big?

Swup Preload plugin could actually preload images that you would define manually in the config (although it seems browsers tend to go through requests made by swup and download images automatically, so not sure if it's needed), and we would have to put some work into that.
