### ISSUE TITLE
Head Plugin , after transition of certain pages (sub-folder) there is a flash with some big icons of the header

### ISSUE THREAD

**Issue by iamalessiopaoletti** [swup/swup#231]
Hi,

After transition of certain pages (on sub-folder) there is a flash with some big icons of the header,
like the css aren't load or reload,

index and others pages:
`<link href="../css/main.css" rel="stylesheet" type="text/css">`

sub-folder pages:
`<link href="../../css/main.css" rel="stylesheet" type="text/css">`

this problem there isn't if I disable the head plugin,
but i need for update the head.

how can I solve?

[https://alessiopaolettidesign.it/ph/it/#wg-title](url)

**Comment by AugustMiller** [comment]
The HEAD plugin is probably removing the first `link` tag and adding the second, because when comparing the text of the two tags, they differ.

Your best bet will be to put a non-relative path in the `href` attribute—for example, if you have a folder structure like this in your web root (`/`):

```
index.html
my-page.html
folder/
    my-subpage.html
css/
    main.css
js/
    main.js
```

…every HTML document can reference the CSS file as `/css/main.css`, without the need to maintain different `../../` prefixes depending on how your pages are organized, hierarchically.
