### ISSUE TITLE
bootstrap navbar class active not update

### ISSUE THREAD

**Issue by Giorgiodir** [swup/swup#232]
Hi guys Someone knows how to solve the problem of the active class on the bootstrap navbar, in practice the page does not update the class but remains active on the previous page.

**Comment by AugustMiller** [comment]
I suspect this is the result of your navigation being outside a declared Swup `container`, or the active classes only being applied with JS on the initial page load (instead of server-side).

There are two options: add your navigation element as a [Swup container](https://swup.js.org/options#containers), or, if that fails to work, investigate how Bootstrap is actually applying those "active" classes, and re-run the logic inside of a [listener on `swup:contentReplaced`](https://swup.js.org/events).

Our ability to troubleshoo is going to be pretty limited without examples of how your site is set up.
