### ISSUE TITLE
Send $_GET data to bypass WordPress Cacheing

### ISSUE THREAD

**Issue by jesserosenfield** [swup/swup#235]
First off- Amazing plugin! Thank you!

I'm using this with WordPress.

Ideally I would like to **omit** the header and footer when SWUP requests a page– the reason being that there is a lot of code in the header that has already been loaded (inlined CSS, javascript, etc) that only bloats the request size of the page when all swup really needs is the `#swup` element.

I can do this easily with PHP:

```
$isswup = false;
if(strtolower($_SERVER['HTTP_X_REQUESTED_WITH']) == 'swup') {
     $isswup = true;   
}

if($isswup == false) {
     get_header();
}
```

But once I'm using the autoptimize or WP Super Cache or whatever cacheing plugin, that PHP conditional logic no longer gets applied.

However, if there is a $_GET parameter, the page will not get cached.

So I'd like to be able to set a $_GET parameter in the `fetch()` request, but NOT actually display that $_GET parameter in the URL that get goes to `window.location` or `popState` / 
 `pushState`

Is this possible or do you see a better alternative?

Thanks!

**Comment by AugustMiller** [comment]
I think the direct answer is that Swup doesn't have native events to expose the underlying `XMLHttpRequest` instance.

You may be able to shim this _outside_ of Swup to inject your own additional parameters, but I would advise against making this kind of low-level change to a built-in prototype.

So you're aware, [there is a first-party "head" plugin](https://github.com/swup/head-plugin) that helps manage changing contents of the `head` element.

By design, Swup doesn't re-download any assets, so you shouldn't see remote CSS + JS being requested more than once, unless the URL differ. The head plugin will intelligently swap out tags based on their final content (so, say you had some in-line CSS like `<style>body { color: coral; }</style>`, and the same `style` tag came down the pipe in a new page, it wouldn't bother removing one and inserting the other, because they're identical.

If your pages are statically cached, there shouldn't be a (significant) performance penalty for some additional markup. The browser parses HTML really fast. 😎

Last note: If you're using a GET param to side-step your cache for the dynamic portions of your page, this may defeat the purpose of the cache, in the first place? (Thinking twice about this… maybe you're just saying there will be two discrete cached pages, one with the bare URL, and one with a static string like `?swup=howdy`, so regular requests _and_ XHR requests hit separately-build pages?)

🦃

**Comment by gmrchk** [comment]
Hi 👋 

I would personally avoid using any WP optimization plugin, if you don't know what it does and how to bend it to your solution, but that's just personal opinion. You can probably work on a speed of your page yourself without third party plugin, if it really turns out to be an issue in a first place.

In case you really want to go with swup adding something to the URL, you can modify swups [`fetch` helper](https://github.com/swup/swup/blob/master/src/helpers/fetch.js#L13). This helper is the code making all the requests, so adding something to the url here won't affect any other parts. You will need to build your own custom swup with `npm run build`.

There might be some issues coming from this custom behaviour. For example, swup checks for redirections by the server (`responseUrl` property set in server response), and in case the url does not match the current one, swup will correct it. [This is the code](https://github.com/swup/swup/blob/master/src/modules/getPageData.js#L11) saving the `responseUrl` for swup to use, where you can remove whatever you're adding to the requested url in a first place. This is only needed in case response from server actually has the `responseUrl` set, which I think only happens in case of redirection, but I'm not sure about that.
