### ISSUE TITLE
Weirdness with SwupHeadPlugin and SwupScriptsPlugin

### ISSUE THREAD

**Issue by aerni** [swup/swup#240]
I'm running into issues with `SwupHeadPlugin` and `SwupScriptsPlugin`. I want to use `SwupHeadPlugin` to update the meta tags of the page when the content is replaced. Now, after the content is replaced, I need to re-run external scripts, that I have no control over.

Now, this is where I'm running into multiple issues, which I try to outline here.

The `SwupScriptsPlugin` generally does what you'd expect it to do. Now, there are cases, where a script adds another script or style tag to the head. This is where things get weird.

Let's be specific. I'm using a cookie consent solution called Iubenda. These are the scripts I need to add to the head:

```html
<script type="text/javascript">
  var _iub = _iub || [];
  _iub.csConfiguration = {
    ...
  };
</script>
<script type="text/javascript" src="//cdn.iubenda.com/cs/iubenda_cs.js" charset="UTF-8" async></script>
```

When the scripts above execute on initial page load, they are adding another two scripts and two style tags to the head:
```html
// Initial scripts
<script type="text/javascript">
  var _iub = _iub || [];
  _iub.csConfiguration = {
    ...
  };
</script>
<script type="text/javascript" src="//cdn.iubenda.com/cs/iubenda_cs.js" charset="UTF-8" async></script>

// Newly added scripts and style tags
<script async="" src="//www.iubenda.com/cookie-solution/confs/js/90646815.js"></script>
<script src="//cdn.iubenda.com/cookie_solution/iubenda_cs/core-460d5dabb86cf85562e6ba39e7ce1a86.js"></script>
<style type="text/css"></style>
<style type="text/css"></style>
```

So far so good. Now, when I start navigating between pages, all the head tags get removed by the `SwupHeadPlugin`. After the content is replaced, the first two scripts are executed again using the `SwupScriptsPlugin`. But this time most of the tags that were added at initial page load are missing:

```html
// Initial scripts with added `async="false"` by the `SwupScriptsPlugin`
<script type="text/javascript" async="false">
  var _iub = _iub || [];
  _iub.csConfiguration = {
    ...
  };
</script>
<script type="text/javascript" src="//cdn.iubenda.com/cs/iubenda_cs.js" charset="UTF-8" async="false"></script>

// Newly added script
<script src="//cdn.iubenda.com/cookie_solution/iubenda_cs/core-460d5dabb86cf85562e6ba39e7ce1a86.js"></script>

// Missing scripts and style tags
<script async="" src="//www.iubenda.com/cookie-solution/confs/js/90646815.js"></script>
<style type="text/css"></style>
<style type="text/css"></style>
```

I've been playing around with it for a while and am really not sure what's happening here.

**Caching Issue**
Another issue concerning scripts that add other tags to the head is with the Swup cache. When navigating back to a previously cached page, the script that was added by another script will be present twice. Once because it's taken from the cache and once because it's added when the base script is executed.

In my case I'm ending up with this:
```html
<script src="//cdn.iubenda.com/cookie_solution/iubenda_cs/core-460d5dabb86cf85562e6ba39e7ce1a86.js"></script>
<script async="false" src="//www.iubenda.com/cookie-solution/confs/js/90646815.js"></script>
<script src="//cdn.iubenda.com/cookie_solution/iubenda_cs/core-460d5dabb86cf85562e6ba39e7ce1a86.js" async="false"></script>
<script type="text/javascript" async="false">
  var _iub = _iub || [];
  _iub.csConfiguration = {
    ...
  };
</script>
<script type="text/javascript" src="//cdn.iubenda.com/cs/iubenda_cs.js" charset="UTF-8" async="false"></script>
```

This is the script that gets added twice:
```html
<script src="//cdn.iubenda.com/cookie_solution/iubenda_cs/core-460d5dabb86cf85562e6ba39e7ce1a86.js"></script>
```

Another thing that's weird here, is that the style tags that were added by the script are missing in the cached version. No idea why.

This is how the cached version should look like:
```html
// Initial scripts
<script type="text/javascript">
  var _iub = _iub || [];
  _iub.csConfiguration = {
    ...
  };
</script>
<script type="text/javascript" src="//cdn.iubenda.com/cs/iubenda_cs.js" charset="UTF-8" async></script>

// Newly added scripts and style tags
<script async="" src="//www.iubenda.com/cookie-solution/confs/js/90646815.js"></script>
<script src="//cdn.iubenda.com/cookie_solution/iubenda_cs/core-460d5dabb86cf85562e6ba39e7ce1a86.js"></script>
<style type="text/css"></style>
<style type="text/css"></style>
```

I hope this all makes sense to you. I tried to explain the issues as good as possible.

**Comment by aerni** [comment]
A potential solution could be to not remove scripts from the `<head>` when they are present on the next page. And also not remove any other tags that were added by this script.

**Comment by gmrchk** [comment]
Hi, sorry for the delay.

I'm guessing we have several issues here:
1. When the cache is enabled, swup caches the first page at startup. At this point, the script didn't make the required changes to the head tag, so kind of incomplete version of the page is saved to the cache. You can avoid that by running `swup.cache.empty()` after the swup init, which will remove the cache record and re-download the page on the next visit (even popstate). But that won't solve the problem, because saving the incomplete page is actually good in this case.
2. The script you inserted (`iubenda`) likely sets some flag on a page on whether it has been initialized yet or not. This means that when scripts-plugin re-runs the script, it will see that it has already been initialized on the page and bail without appending the other tags. At least that's what I would do.
3. The scripts-plugin actually modifies scripts when it executes them (it adds `async="false"` attribute). Honestly, I'm not even sure if this is needed, but anyway. When head-plugin compares the head content, the two script tags (one with and one without the async attribute) don't get detected as the same anymore, so it probably ends up in some mashup. This is a bug that should be addressed, but I don't want to invest time in these plugins. 

> A potential solution could be to not remove scripts from the <head> when they are present on the next page. And also not remove any other tags that were added by this script.

The head-plugin doesn't replace tags that are present in the next head tag already, but knowing what was added by the scripts is impossible. 

My best recommendation is not to use the two plugins at all if possible. The cookies solution probably creates some elements that can be present across page transitions outside of the swup containers, so there might not be a need to re-run the cookie script at all. Could you provide a demo to get some more context?
