### ISSUE TITLE
Different transitions for different links possible?

### ISSUE THREAD

**Issue by folkfreund** [swup/swup#249]
Thanks for this awesome lib!
Is there a possibility to have different links trigger different kind of transitions? I understood how to perform different transitions on different containers. But I would like to have different transitions on the same container, depending on the link that was clicked.
Any hint would be helpful :-)

**Comment by covey-alistair** [comment]
When transitioning, Swup adds a class starting `'to-'` to `<html>`, with a classified string of the path you are transitioning to. For example, if you click on a link to `example.com/test/example1`, `<html>` should receive a class `'to-test-example1'` whilst transitioning.

This makes it easy to change the transition based on the link you are going to, but it's a bit more difficult if you want more context between two pages. For this, I add a similar functionality for `'from-'`. This way you can use combinations of `'from-'` and `'to-'` in order to target a transition between two particular pages. My additions below (note, this uses jQuery but would be easy to modify for vanilla JS):

```javascript
// on document ready
swup.on('transitionStart', fromClass)
swup.on('transitionEnd', removeFromClass)

function fromClass() {
  let path = window.location.pathname + window.location.search
  if (path[0] !== '/') {
    path = '/' + path
  }
  $('html').addClass('from-' + classify(path))
}

function removeFromClass() {
  $('html').removeClass(function(i, className) {
    return (className.match(/(^|\s)from-\S+/g) || []).join(' ')
  })
}

// convert url into swup class
function classify(text) {
  let output = text
    .toString()
    .toLowerCase()
    .replace(/\s+/g, '-')
    .replace(/\//g, '-')
    .replace(/[^\w-]+/g, '')
    .replace(/--+/g, '-')
    .replace(/^-+/, '')
    .replace(/-+$/, '')
  if (output[0] === '/') output = output.splice(1)
  if (output === '') output = 'homepage'
  return output
}
```

**Comment by gmrchk** [comment]
FYI, you can use classes on `body` element + [body class plugin](https://swup.js.org/plugins/body-class-plugin) to know what page are you in, but I kinda like what @covey-alistair did.

**Comment by folkfreund** [comment]
Thanks a lot for your interesting suggestions. Meanwhile I found out about "data-swup-transition" attribute, which I was not aware of. It's a bit hidden in the docs, just appears in "How it works", which I didn't read again after it worked for me :-) 
Thanks again for this wonderful little helper to make a real difference!
