### ISSUE TITLE
Swup with Rails error: 'Cannot set property 'responseURL' of null'

### ISSUE THREAD

**Issue by matted-dev** [swup/swup#251]
Using Rails 6 & Webpack, I've tried installing through npm and including from unpkg.

I'm requiring, then initializing with
`const swup = new Swup();`

And using the markup & css from the example
```html
<main id="swup" class="transition-fade">
      <h1>This is homepage</h1>
      <p>
        Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut
        labore et dolore magna aliqua.
      </p>
      <a href="/someOtherPage">Go to other page</a>
```

Any starting point as to what could be causing the error? Other issues point to setup/naming errors but can't see that here

**Comment by tridnguyen** [comment]
@matted-dev I'm guessing you're including your `application.js` in the head.  The problem is when you run swup: `const swup = new Swup();` it's looking for an element with the `id="swup"` attribute, but your `application.js` in the head  executes before the html is rendered, so the element doesn't exist on the page yet.

The simple solutions would be to move your `application.js` script tag to the end of the `body` tag (better for page load performance anyway).

If you're unable to move it to the end of the body tag for some reason, you can just leave it in the `head` tag and add a `<script> const swup = new Swup(); </script>` at the end of your body tag so that it runs after the element exists in the DOM.

**Comment by gmrchk** [comment]
In general, this error refers to swup not being able to cache the page (I know, the error could be better). Swup also caches the initial page, where the error could be what @tridnguyen referred to. Another option would be that you're using a preload plugin which tries to preload an invalid page.
