### ISSUE TITLE
TypeError when going to a non-Swup page with [data-no-swup] set

### ISSUE THREAD

**Issue by ajmnz** [swup/swup#257]
I'm building a website where some pages have Swup and others don't.
When in a page with a `#swup` container, if you try an access another page which doesn't have a Swup container it throws the following error:

> Uncaught TypeError: Cannot set property 'responseURL' of null
>     at e (swup.min.js:1)
>     at new e (swup.min.js:1)
>     at app.js:2
> e @ swup.min.js:1
> e @ swup.min.js:1
> (anonymous) @ app.js:2

Is that a common thing? I've got `data-no-swup` set to the link and still the same error.
**`/home`**
```
<body>
    <div class="menu">
        // Some menu items
     </div>
     //Some content WITHOUT Swup
</body>
```
**`/test`**
```
<body>
    <div class="menu">
        <li><a href="/home" data-no-swup></a></li>
    </div>
    <div id="#swup">
        // Content
    </div>
</body>
```
**`app.js`**
```
const swup = new Swup({
    plugins: [new SwupFadeTheme()],
});
init();
swup.on('contentReplaced', init);
function init() {
     console.log('yep')
}
```

**Comment by gmrchk** [comment]
Hey, I'm guessing this error occurs after the browser natively navigates to the page without swup container(s), where this error will be thrown when you try to enable swup, since there is no container for swup. A fix would be to check if the container exists on a page before enabling swup. 
```javascript
if (document.getElementById('swup')) {
    ...
}
```
Maybe I misunderstand why are you trying to have some pages in swup and some not tho.
