### ISSUE TITLE
Using Swup in MeteorJS

### ISSUE THREAD

**Issue by ramprakashram** [swup/swup#259]
**Describe your issue**:
I am trying to use swup in my PWA app created in MeteorJS to show page transitions like a native App.

I add unpkg link for swup in main.html.
And i called `const swup = Swup();` in the main.html.
I have a component inside in which i have added the swup id to a div and a class name.
But i am getting this error, whenever i am running the app.

> Uncaught TypeError: Cannot set property 'responseURL' of null.

**Comment by gmrchk** [comment]
Hey @ramprakashram, this likely means that the swup id is simply not there when swup is starting up. You are probably trying to enable swup before the element with swup id is present on the page. Meteor likely has some method that would be executed when the page/app is ready, but since I never used it myself, I'm not able to provide details. Are you aware of such option?
