### ISSUE TITLE
Swup and Moodle:  ajax blocks don't load

### ISSUE THREAD

**Issue by gothadrummer** [swup/swup#261]
Hello everyone,

and huge thanks for this amazing framework!
I'm trying to improve the user experience by using swup in a [Moodle](https://moodle.org) theme, and the transition works, but unless you manually refresh the page, main blocks never load:

**Main page:**

![image](https://user-images.githubusercontent.com/64462891/80464053-83775b00-8939-11ea-80e6-4409581a0ecc.png)

**Private files page:**

![image](https://user-images.githubusercontent.com/64462891/80463882-372c1b00-8939-11ea-9eb6-f74fbf59abec.png)

The issue appears with a minimal configuration:
- swup.js loaded in the theme config.php header
- main.js loaded in the theme config.php footer:

```javascript
// With window load event or on its own
const swup = Swup({
   containers: ["#page-wrapper"], // main div
   cache: false // this works for web services within Moodle pages, random contents ("yes or no?" API for instance) get updated, but the issue remains for ajax loaded blocks
});
```

I tried to use the Scripts Plugin playing around with its options, but many errors appeared (is it because Moodle centralizes all js contents – AMD, Yui lib, etc. – in a file called "first.js", from the lib file "javascript.php", and provide useful data like session key, username and rights, etc.?)

I also tried to use the Debug plugin, and [reload pages](https://swup.js.org/api/methods) using the clickLink event delegateTarget href as the passed url, but the problem persists.

From my understanding, I need to find a way to load complex javascript html using swup's built in popstate / XMLHttpRequest system, but I can't figure it out.

I would really appreciate any hints or direction.

Huge thanks in advance for your help, and thank you for reading!

**Comment by yanivz** [comment]
I have this issue too

**Comment by gmrchk** [comment]
Hey guys! Yep, scripts plugin could help, but since there is a lot of scripts in Moodle that we don't really know what they do, I wouldn't go that way.
It's clear that we need to reload scripts used on the page, as described [here](https://swup.js.org/getting-started/reloading-javascript). However, what scripts need to be reloaded, that's something to figure out. I have a hunch that Moodle would have some unified API to do that, but I don't know. I think the best place to find out would be on some Moodle forum, where Moodle experts could help. 

If you do ask elsewhere, please, post a link back here.
