### ISSUE TITLE
Anchor link doesn't work?

### ISSUE THREAD

**Issue by Jonatan-r** [swup/swup#267]
**Describe your issue**:
My link:

```html 
<a href="#videos"><button class="..."><span>VIDEO</span></button></a>
```

_Expected behaviour:_
On click, it would jump or scroll to the div with the id "videos". Which is does, when swup.js isn't added. 

_Actual behaviour:_ 
Nothing. The url does update from https://site.dk/page to https://site.dk/page#videoes,
but besides that nothing happens

**Swup config or any additional relevant code used**:

```javascript
const options = {
        cache: false,
        animateHistoryBrowsing: true,
        linkSelector:
            'a[href^="' +
            window.location.origin +
            '"]:not([data-no-swup],[data-fancybox]), a[href^="/"]:not([data-no-swup],[data-fancybox]), a[href^="#"]:not([data-no-swup],[data-fancybox])',
        requestHeaders: {
        "X-Requested-With": "swup", // so we can tell request comes from swup
        Accept: "text/html, application/xhtml+xml, application/json" // to explicitly define what response we are expecting
        }
    };
    const swup = new Swup(options);
```

If I've understood it correctly, this anchor link should be a valid linkSelector (`a[href^="#"]`) and so it should be handled bu swup.js and make it jump to the div?

I might be missing something here? Sorry if that's the case. I hope you can help me out. Thanks a lot! 

**Before creating this issue, did you think of...**:
- [x] Have you checked closed issues for similar/related problems.
- [x] Have you provided all helpful information available? 
- [x] Have you considered creating a demo so we can help you better?

**Comment by Jonatan-r** [comment]
So.. Switched to Barba.js... Sorry. Works like a charm. Nothing but 1 min initial setup needed :)

**Comment by foxnoodles** [comment]
Any fix to this? Im having the exact same issue.

**Comment by gmrchk** [comment]
There are use cases when scrolling on a page doesn't need to be handled at all, eg. some full-screen pages without any scroll. That's why swup doesn't come bundled with the scroll controls, but instead has a [Scroll Plugin](https://swup.js.org/plugins/scroll-plugin) which adds that functionality with some spring-based animation stuff on top as well, tho it can be disabled. 

It really helps to read at least through the initial [Getting Started](https://swup.js.org/getting-started) text folks, instead of blaming the library.

**Comment by foxnoodles** [comment]
Ok chill bruh. Nobodys blaming anyone here I asked a question, I don't see an answer. Everyone who managed to install swup as read the getting started docs yet we are here. Now, do you have a direct ansswer to my or OP-s question or what?

**Comment by gmrchk** [comment]
I might have sounded too harsh for 2021 😄 that was not my intention. The point is - read the docs. If you haven't known about the Scroll plugin, which is literally referenced on the first page, you haven't read the docs. 

Without the plugin swup simply doesn't know how to scroll. Changing `linkSelector`  option to not take the hash links into account, or adding the `data-no-swup` to those links will also do what you want since swup won't handle those links at all and it will fall back to the default browser behavior. 

The scroll plugin has its own set of options. The implementation of the plugin is a bit opinionated but should cover most use cases. These options can be also changed on the go if needed with something like...

```javascript
const swup = new Swup(...);
swup.plugins.find(p => p.name === 'ScrollPlugin').options.animateScroll = true;
```

If something is not clear from the docs, feel free to edit it. There is a button on the bottom of each page. 
Surely I'm not the best person to tell whether something is not clear.

**Comment by foxnoodles** [comment]
Oh nice, I'm glad we cleared that up :D 

So um, first things first, I've read about Scroll Plugin before even using swup but I thought it was just for adding scroll behavior after transition ends (or before it starts) which can be achieved simply by calling window.scrollto smooth in swup.on('contentReplaced'); no plugin needed.

Secondly I was not able to get linkSelector working at all, and [data-no-swup] does not wok for me either. No idea why :/ I just add them to a tag as a regular data attribute but no go.

**Comment by gmrchk** [comment]
Swup `event.preventDefault`s any click on a link that it should react to, based on the `linkSelector`, to prevent a native page reload. It could of course exclude the links with `#` on the same page somehow and let the browser do its native thing by default, but that would lead to inconsistencies in the behavior, and make implementing any custom scroll behavior (with swup events) difficult because any custom logic (including Scroll plugin) would have to account for these exceptions. 

But even if we let swup scroll to the hash element on the same page natively, it gets more complicated once we go the another page with a hash. At that point, Swup must `preventDefault` the event, wait until the transition is finished, and then scroll to the correct position. There is no way to preserve native functionality there. 

So that's basically why the scroll plugin exists, to mimic this native behavior even with transitions. Surely you can use the animated settings of the plugin (which adds it a nicer spring animation which I personally prefer over the `window.scrollto` smooth), but that's just a cherry on top and the main purpose of the plugin is to restore the nativy scroll behavior we were forced to break. As mentioned, not all sites deal with scrolling, so that's why it's rather an optional plugin, instead of built in feature of swup as it used to be in v1. 

Shall we make it clearer in the docs somehow what the purpose of the plugin is? Could you make a PR with a suggestion that would be clear for someone new to Swup? 

---

`linkSelector` is like a gateway to swup, which by default excludes `data-no-swup` elements (eg. `'a[href^="' +
    window.location.origin +
    '"]:not([data-no-swup]), a[href^="/"]:not([data-no-swup]), a[href^="#"]:not([data-no-swup])'`). Whatever link doesn't match that selector can't be processed by any of the swup code at all, so swup can't be at faul. You might have some other problem at hand, or the option is set incorrectly? 

---

```javascript
swup.on('animationOutStart', () => {
	const scrollPlugin = swup.findPlugin('ScrollPlugin');
	scrollPlugin.options.animateScroll = false;
});

swup.on('animationInDone', () => {
	const scrollPlugin = swup.findPlugin('ScrollPlugin');
	scrollPlugin.options.animateScroll = true;
});
```
I've used something similar before myself too when I wanted to only animate the scrolling on the same page but not during the transitions. 👍
