### ISSUE TITLE
Doesn't work with django

### ISSUE THREAD

**Issue by RajPorus19** [swup/swup#281]
Is there a work around for these kind of href ?
 \<a href="{% url 'home' %}"></a>

Because it seems it only works if you have tags like that:
\<a href="/home.html"></a>

**Comment by AugustMiller** [comment]
Swup depends on fully-rendered HTML in order to parse URLs. Is your application outputting the `{% url %}` helper tag in HTML, or is that text being passed all the way to the front-end?

This looks like a server-side template, which Swup should never need to interact with—my assumption is that this would be interpreted, rendered, and delivered by Django with a proper URL substituted for the template tag.

Could you elaborate on where you're seeing `{% url 'home' %}`?

**Comment by gmrchk** [comment]
Closing as part of the cleanup of old issues. Feel free to open a new issue with a more extensive description.
