### ISSUE TITLE
Add to container options?

### ISSUE THREAD

**Issue by jacccccc** [swup/swup#311]
i'm trying to add another option for the containers, 

from the the docs:

const options = {
  containers: ["#swup"]
};

now im assuming if i wanted to add another option, it would look like this?

const options = {
  containers: ["#swup", "#title"]
};

but once i pass the options into my constructor:

const swup = new Swup(options);

my animations no longer happen

am i adding to the options incorrectly? it would be nice if there was an example for adding to the options in the doc since im probably not the only rookie using swup

anyways thanks for any help!

**Comment by gmrchk** [comment]
Hi, that's really a JavaScript basics of how to use arrays or selectors we're discussing. We really can't be going into that much detail in docs for everything.

In any way, you're doing it right. If this change breaks the transition, the problem is probably that you're missing one of the containers on the page. Errors in the console will likely point to that.
