### ISSUE TITLE
Issue when clicking on a link too fast or before transition ends: Cannot set property 'content' of null

### ISSUE THREAD

**Issue by elisabetperez** [swup/swup#319]
I have a problem when I move back and forth from a link to another. If I do it too fast, I get a `lib_detect.js:41 Uncaught (in promise) TypeError: Cannot set property 'content' of null`. The pages load correctly though, but I get that error in my Console.

I'm also experiencing an issue when going from one page to a language version of that page (docs/en/ to docs/fr/). I modified the link_selector so it considers all links, but when clicking on a language link right after the page has had the content replaced and animation has ended, the URL gets all messed up and removes part of that URL (changes the URL to /fr/ instead of docs/fr/ or even changes it to /docs/fr/fr/fr). Hrefs for those links are relative links, such as '../' or '../fr'.

Any thing I might be missing?

**Comment by daun** [comment]
Swup works better with non-relative urls, i.e. without `../`.

**Comment by elisabetperez** [comment]
@daun I noticed, yeah. I need to leave the URLs like that at least for now, so I wonder if there's any workarounds for this 🤷

**Comment by daun** [comment]
I'd go the JS route, iterate over all links on load and replace their href with an optimized href, i.e. one without relative folder traversal.

**Comment by gmrchk** [comment]
Hi, the first problem is likely directly connected to the second one, since the links make swup request wrong URLs, so I will be addressing the second problem directly. 

It's not really that swup works better with absolute links. Relative links are not used on the web in general for various reasons, so swup doesn't support them, even tho it easily could. 

Your best bet is to use absolute-from-root links, like `<a href="/fr/docs">...</a>`. These will work without specifying a hardcoded domain, so there should not be any problem to use them. 

If the reason you would like to keep the relative links is that you're browsing the site "as files" (eg. `file://` in URL) on your machine, you can use a package like [http-server](https://www.npmjs.com/package/http-server) to start a server from any folder instead, which will make the links I suggested work as if the site was already hosted. 

Hope that helps. Feel free to reopen the issue if needed.
