### ISSUE TITLE
Don't works with standard wordpress plugin like contact form 7

### ISSUE THREAD

**Issue by afmarchetti** [swup/swup#394]
Swup is awesome!
unfortunately the pain to make it work with some simple wordpress plugin it's a lot.

I had install the scripts plugin but this approach not reload / reinitialize the contact form 7 js input control.

if i realod the page manually works, you can see a demo of the problem here, try to change the page and go back to the contact and you will se the error:

http://nextlevelskills.it/demo2/contatti/

what i can do to make it works with wordpress ?

many thanks

**Comment by AugustMiller** [comment]
I can appreciate the desire to have a library of "recipes" for this, but I don't think we'd _ever_ be able to cover the breadth and depth of possible collisions with existing software. It's also complicated by `init` logic changing over the course of its life—so what happens when suddenly _our_ documentation for these edge-cases is out of date?

Most of the Wordpress ecosystem relies on the web application behaving a certain, predictable way (throwing out and reloading the page on each request)—and Swup subverts that. So instead of having authoritative how-tos, we try and provide agnostic implementation tips that (may) demand some degree of curiosity and creativity from developers.

If you would like to share your experience integrating with WP + CF7, I encourage you to post a new Discussion. 👍 A community-led repository of information will go a lot farther than anything we can provide!
