### ISSUE TITLE
Swup for php pages

### ISSUE THREAD

**Issue by denii18** [swup/swup#433]
Hi! Can I use swup for php pages?

**Comment by daun** [comment]
Using PHP should be fine. swup is a frontend library, it doesn't care about the backend language you're using as long as the output is valid HTML to be displayed in a browser.

**Comment by denii18** [comment]
Hi! Thank you for your response but I saw that if u want to use swup you need to put a '/' before the name of the page for example <a href="/index.html"></a>, and if I put a '/' in front of a php page the link doesn't work.
    Pe luni, 30 mai 2022, 00:23:38 EEST, Philipp Daun ***@***.***> a scris:  
 
 


Using PHP should be fine. swup is a frontend library, it doesn't care about the backend language you're using as long as the output is valid HTML to be displayed in a browser.

**Comment by daun** [comment]
Exactly, swup requires absolute urls with a leading slash. When you add them, you'll need to make sure that you include all parent folders up to the webroot in the url. My guess is that you ended up with incorrect URLs that are missing parts.

Since this is not an issue with swup, I'd recommend asking for further help on StackOverflow.
