### ISSUE TITLE
Handle non-http protocols with new `ignoreLinks` option

### ISSUE THREAD

**Issue by daun** [swup/swup#551]
The upcoming implementation of `ignoreLinks` has one flaw: it doesn't ignore links with protocols like `tel:` or `mailto:`. We'll need to add that check before the release and add tests as well.

Edit: Actually, it does. We're checking for `link.origin` and comparing to `location.origin`, that includes the protocol. Still, we should make sure it's either http or https in any case.

```js
new URL(document.URL, document.baseURI)
new URL(window.location.pathname, document.baseURI)
```

Some questions to ask:

- Should we move the `origin` check into a separate function that cannot be overriden? I'm actually not sure what the advantage is of allowing cross-origin requests
- Should we switch to the native `URL` object instead of swup's `Link` class? Makes more sense to me
- Maybe look for inspiration in [Turbo's URL module](https://github.com/hotwired/turbo/blob/main/src/core/url.ts)

**Comment by hirasso** [comment]
Right! Good catch!

**Comment by hirasso** [comment]
Finally found some time investigating this. Indeed, `el.origin` is `null` for `mailto:` or `tel:` links.

> Should we move the origin check into a separate function that cannot be overriden? I'm actually not sure what the advantage is of allowing cross-origin requests

Yes, let's do that. We could just do the `origin` check directly before the `this.triggerWillOpenNewWindow(linkEl)` conditional and return early if it doesn't match

> Should we switch to the native URL object instead of swup's Link class? Makes more sense to me

It really feels like swups `Link` class only exists because of legacy browsers. If we are fine with [the browser support](https://caniuse.com/url), I don't have any other objections against using the `URL`API.
