### ISSUE TITLE
Garbage Collector for `swup.cache`

### ISSUE THREAD

**Issue by hirasso** [swup/swup#602]
**Describe the problem**

On very large websites the cache can become a problem on less-powerful end devices. It's basically be a built-in memory-leak. I would propose to introduce a configurable garbage collector.

**Describe the proposed solution**

- [x] #603 
- [ ] ~Every time a new page is added to the cache, clean up old pages~
- [ ] ~The amount of pages allowed in the cache should be configurable through an option~
- [ ] ~There should be a way for pages to be ignored by the garbage collector (maybe a callback that will set a property `persist` in `PageHtmlData`?)~

The above mechanism won't be implemented, instead see #607

**Comment by gmrchk** [comment]
I've never had any issues with this, and there are much much larger applications that run in browsers nowadays. On the other hand, I've always had a "beast" of a machine, so my experience is probably not the one of a usual user. 

Since this is not something that would always be needed, it could probably be implemented in a form of a plugin, which would just access the cache every now and then (we can brainstorm the logic here) and remove the oldest records. What we're missing in the cache is the last update timestamp tho, which needs to be added to Swup.

**Comment by daun** [comment]
I've also never found this to be an issue across many swup projects, but I understand that it can become one under certain circumstances. It's an array of very simple objects with strings and no DOM elements in them, so I wouldn't worry about the memory part but I get the concern.

What I'd find more useful is purging the cache after a certain amount of time to avoid stale data. Making this a plugin — Cache++ with some sort of filtering or callback — would feel right to me, in terms of scope and complexity.  Is anything required from the core side to make that happen? It can already hook into `pageCached` to add the timestamp, and into `pageVisit` to purge the entries.

**Comment by daun** [comment]
Switching to a `Map` for the cache entries would make sense to allow easier iteration, slicing, sorting, etc.

**Comment by hirasso** [comment]
Actually, thinking about this further, I would prefer to introduce a very slim timestamp-based  cache invalidation mechanism in swups core instead of a separate plugin. I think an increase in package size is ok where it really makes sense. Or what would be the advantage of having this in a separate plugin, apart from core bundle size, @daun ?

**Comment by daun** [comment]
Conceptually speaking, given how almost everything in swup is a plugin, the whole cache **could** be a plugin. It's debatable if it **should** be a plugin since 90% of all projects would install a cache plugin anyway, but architecturally it'd make sense, I guess. I don't think we should rip out the cache since it's very useful and popular, but I think we shouldn't let it get much more complex.

> I think an increase in package size is ok where it really makes sense.

I agree! It's not about file size so much as about complexity and code we need to maintain going forward. I'm all in favor of adding code if it means it makes swup more flexible and adaptable. In this case, the most flexible solution would be making sure plugins can easily modify cache contents and let them do it. Other libraries or frameworks use cache adapters, xhr-fetch adapters, etc, to do this, but swup plugins are pretty close conceptually. That way, for my next project with weird requirements I could easily write a custom unpublished cache plugin with very specific invalidation logic and be done in a few hours, instead of waiting for swup to implement the specific logic I need.

**Comment by daun** [comment]
One way of testing this would be for you to write the desired logic into the core and create a PR. We'll see if it feels like a good fit or if it should be extracted into a plugin.

**Comment by gmrchk** [comment]
I don't think moving the cache out of the Swup core is an option. It's just too essential to the way it works overall, but I agree that it should rather provide a good API to manipulate it and have any helpful information as well, rather than have a logic to do things out of the box.
For example, the logic related to the `cache` option is possibly unnecessary and makes the [core more complex](https://github.com/swup/swup/blob/master/src/modules/renderPage.ts#L42-L45C4). What it essentially does is empty the cache on every page transition. I would consider removing the option with an alternative solution like a plugin or simple instructions on how to achieve the same with Swup events in a few lines.

**Comment by hirasso** [comment]
For the plugin solution I would step back for now and let you guys try.

**Comment by daun** [comment]
The thing @gmrchk linked to in `renderPage` is one I'd like to solve with this as well. Using the cache for temporary data (used for preloading and getting the new content in the body class and head plugins) feels off. We should find another way to get the current and new page objects without using the cache even if disabled only to then clear it if it's disabled. I'm sure we'll find a nice and simple solution 🤠

**Comment by daun** [comment]
How about we

- add a `pageCached` event
- make sure `cacheUrl` can overwrite/update existing entries or provide an `updateEntry` method
- add an `invalidateCache` or similar method that takes a filter function and removes all entries that return `true` for that function

Would that be enough to allow plugins to implement their own logic?

**Comment by mskocik** [comment]
Adding my 2 cents:

- I always disable the cache. Even on static site with long pages (by long I mean very often 10+ A4 pages full of text)
- Would be nice to have configurable cache size limit
- Would be great if cache wasn't as a part of core logic. Doesn't really make sense.

**Comment by daun** [comment]
@mskocik Interesting. Do you disable the cache **because** it doesn't have a size limit or what keeps you from enabling it?

**Comment by mskocik** [comment]
@daun on the static site I mentioned before, no limit was the reason why I disable cache. When you think about it, cache has meaning only on `history.back`. Otherwise it's just wasted memory.

In other PHP apps (internal tools) which are completely ajaxified (full page navigation by swup, forms submits etc by additional ajax handler). So I can do edit stuff and go back (using browser back button). But I need to see updated data on going back, not the cached version. Because I had it enabled in the beginning, but it was confusing for the users.

**Comment by gmrchk** [comment]
I agree with @mskocik, the cache being disabled altogether for more dynamic sites is also something I've been using a lot in the past. Depends on the use case here, but some sites simply change the content too often for it to be cached at all (blogs, etc.).

**Comment by daun** [comment]
Closed in PR #689
