### ISSUE TITLE
`getAnchorElement` sometimes failes

### ISSUE THREAD

**Issue by hirasso** [swup/swup#652]
**Description of the issue**

I just noticed that some of the anchor links on the swup docs site are not working. Right now it's broken for all links that contain a question mark, like "Having Trouble?" or "Want to Contribute?".

Turns out this happens due to swup [transforming the hash](https://github.com/swup/swup/blob/master/src/modules/getAnchorElement.ts#L12-L13) before it attempts to match it against an element:

```js
hash = decodeURIComponent(hash);
hash = escapeCssIdentifier(hash);
```

So `having-trouble%3F` for example is being converted to `having-trouble\?` and thus can't match the `id` that actually is `having-trouble%3F`.

@daun, would you mind taking a look? Do you still remember why you introduced these transformations?

**Comment by daun** [comment]
We have tests in place to check this function with UTF anchors. I've researched this a bit back then and that's how to convert between hash and CSS selector encodings.

Could this have gone wrong somewhere else? E.g. when creating and encoding the hashes?

**Comment by daun** [comment]
I think I understand now. IDs aren't supposed to be url-encoded. Only the hash itself is -- since it's part of a URL. If a character can't be a valid part of an ID, we should strip it or slugify it as "-" instead of url-encoding it.

**Comment by daun** [comment]
The solution here is either not url-encoding the id or double-encoding the anchor in the link. Linking to `a%3F` would require an id of `a?`. To make the ID `a3%F` work, the link would need to go to `a#%253F` (since the percent sign itself has to be encoded and decoded itself).

**Comment by hirasso** [comment]
Interesting. When I deactivate swup and use the native browser behavior, it works. Shouldn't swup work just like the browser?

**Comment by hirasso** [comment]
Maybe we could try to match an element before doing the conversion and if one is found return early?

**Comment by daun** [comment]
Let me do some more research on the expected behaviour here — if browsers have a way of detecting url-encoded id attributes and skipping the decoding in those cases, we should definitely implement that as well. 

Simply not converting it is not an option as it would lead to JS exceptions from the CSS selector engine, complaining about invalid CSS attribute characters. That's the reason we've implemented this in the first place: it'll lead to invalid selector syntax. We could wrap a try-catch around it, but that would feel weird.

**Comment by daun** [comment]
Turns out browser behavior isn't consistent here so there's no way of exactly reproducing it.

- **WebKit** will first look for the raw hash, then for the url-decoded version. This is identical for id and name attributes. In your example, it would choose the id attribute `having-trouble%3F` over `having-trouble?`, but accept both.
- **Firefox** treats id attributes the same as WebKit.
- In **Firefox**, named anchors show the reversed behaviour: it seems to be storing a url-decoded version of the name attribute in its DOM tree and match that to the raw value of the hash, ignoring the decoded version altogether.

I'll try to come up with updated logic we can use to get as close as possible.

Do you prefer...

- a) sticking with WebKit's implementation or
- b) trying to cover as many edge cases as possible?

For the sake of simplicity and bundle size, I'd suggest a) 🥯

**Comment by hirasso** [comment]
Option A sounds perfect! 👍👍
